server.port=6799
# 自定义静态资源目录
isDev = 1
outer.static.resources=D:/desk/comfyui_batch_processing/comfyui_static

#1 自动开启； 0 开闭自动开启；项目默认地址 127.0.0.1:6799
auto-open=1






#日志位置
logging.file=logs/base.log
server.tomcat.max-http-post-size=10MB
server.max-http-header-size=16KB

spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.jackson.serialization.indent_output=true
#开发环境配置文件选择
#spring.profiles.active=pro
#spring.profiles.active=dev
#拦截器开关

server.servlet.context-path:/
server.tomcat.uri-encoding= UTF-8
server.use-forward-headers = true
server.tomcat.remote-ip-header = X-Real-IP
server.tomcat.protocol-header = X-Forwarded-Proto
#日志级别
logging.level.com.zyz=INFO
logging.level.root=INFO


#框架配置
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.druid.initial-size=20
spring.datasource.druid.min-idle=20
spring.datasource.druid.max-active=100
spring.datasource.druid.stat-view-servlet.allow=true
spring.datasource.druid.max-wait=60000
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.time-between-eviction-runs-millis=60000
spring.datasource.druid.min-evictable-idle-time-millis=30000
spring.datasource.druid.validation-query=select 'x'
#spring.datasource.druid.exception-sorter=true
spring.datasource.druid.test-on-borrow=false


#mybatis-plus配置
mybatis-plus.mapper-locations=classpath:/com/zyz/mapper/*Mapper.xml
mybatis-plus.typeAliasesPackage= com.zyz.pojo
#主键类型
#0:"数据库ID自增",
#1:"用户输入ID"
#2:"全局唯一ID (数字类型唯一ID)"
#3:"全局唯一ID UUID";
mybatis-plus.global-config.id-type= 0
#字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
mybatis-plus.global-config.field-strategy=2
mybatis-plus.global-config.db-column-underline= true
mybatis-plus.global-config.key-generator= com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
mybatis-plus.global-config.logic-delete-value= 0
mybatis-plus.global-config.logic-not-delete-value= 1
mybatis-plus.global-config.db-type= mysql
mybatis-plus.configuration.map-underscore-to-camel-case= true
mybatis-plus.configuration.cache-enabled= false
#文件上传
spring.servlet.multipart.max-file-size= 10240MB
spring.servlet.multipart.max-request-size=10240MB

#数据库地址
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/comfyui?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password= root


